### ISSUE TITLE
Add HTML output

### ISSUE THREAD

**Issue by nuest** [o2r-project/o2r-web-api#1]
It would be helpful to also publish the API as a HTML document, ideally as a GH-page.

**Comment by JanKoppe** [comment]
I'm not sure what the best practice here would be. `mkdocs` would be a very comfortable tool to render our markdown documents in a "ReadTheDocs" style. This can be achieved with moving the files in a new folder and adding a single `yaml` file.

But, providing the HTML rendered version as a GH-page would be a bit tedious, because we would have to manually branch off and restructure the files.

Maybe we can automate this in a Makefile (render, branch/checkkout, move files, commit, push). I need to look into this.

**Comment by JanKoppe** [comment]
https://mwop.net/blog/2016-01-29-automating-gh-pages.html

This could be just what we need.

**Comment by nuest** [comment]
That looks really useful, good find.

**Comment by nuest** [comment]
https://docs.figshare.com/api/ looks good - also a related API useful to take a look at.

**Comment by JanKoppe** [comment]
changes that are made to the master branch will now be automatically deployed to http://o2r.info/o2r-web-api/
